name: .NET

on:
  workflow_dispatch: # manual trigger
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION: TOS.CQRS.sln
  NUGET_SOURCE: https://nuget.pkg.github.com/ogaiht/index.json
  OWNER: ogaiht

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: '5.x'
    
    - name: Calculate Build Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.11
      
    - name: Set VERSION
      run: |
        echo ${{ steps.gitversion.outputs.semVer }}.${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}-${{ steps.gitversion.outputs.ShortSha}}
        echo "VERSION=$(echo ${{ steps.gitversion.outputs.semVer }}.${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}-$(echo ${{ steps.gitversion.outputs.ShortSha}} | sed 's/^[0-9]*//'))" >> $GITHUB_ENV
        echo "SHORT_VERSION=$(echo ${{ steps.gitversion.outputs.semVer }})" >> $GITHUB_ENV
        
    - name: Print VERSION
      run: echo "VERSION - $VERSION"
      
#    - name: Authenticate to GitHub Packages
#      run: dotnet nuget add source --username $OWNER --password ${{ secrets.PACKAGE_CONSUMER_TOKEN }} --store-password-in-clear-text --name github $NUGET_SOURCE
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build $SOLUTION --no-restore /property:Configuration=Release /property:Version=$SHORT_VERSION
      
    - name: Test
      run: dotnet test $SOLUTION --verbosity normal /property:CollectionCoverage=true /property:CoverletOutputFormat=opencover

    - name: Creating Packages
      run: dotnet pack $SOLUTION --no-restore /property:Configuration=Release /property:Version=$SHORT_VERSION  /property:NuGetVersion=$SHORT_VERSION -o out

    - name: Push Packages
      run: dotnet nuget push ${{ github.workspace }}/out/*.nupkg --skip-duplicate --no-symbols true --source $NUGET_SOURCE --api-key ${{ secrets.PACKAGE_PUBLISHER_TOKEN }}
